[pytest]
filterwarnings =
    ignore:Call to deprecated create function.*:DeprecationWarning
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:SelectableGroups dict interface is deprecated:DeprecationWarning
    ignore:.*pkg_resources is deprecated as an API:DeprecationWarning
asyncio_mode=auto
